name: patapata_firebase_dynamic_links
description: This package is a plugin for Patapata that adds support for Firebase Dynamic Links to your Patapata app.
version: 1.0.0
publish_to: none
homepage: https://github.com/gree/patapata
repository: https://github.com/gree/patapata/tree/main/packages/patapata_firebase_dynamic_links

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  patapata_core: ^1.1.0

  patapata_firebase_core: ^1.1.0

  firebase_dynamic_links: ^4.17.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
