name: patapata_firebase_remote_config
description: This package is a plugin for Patapata that adds support for Firebase Remote Config to your Patapata app.
version: 1.2.0
homepage: https://github.com/gree/patapata
repository: https://github.com/gree/patapata/tree/main/packages/patapata_firebase_remote_config

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  patapata_core: ^1.2.0

  patapata_firebase_core: ^1.2.0

  firebase_remote_config: ^5.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
